- data/game-documents/aryl-ether/guided-by-the-sun.md
- data/game-documents/evilhat/fate-accelerated.md
- data/game-documents/evilhat/fate-adversary-toolkit.md
- data/game-documents/evilhat/fate-condensed.md
- data/game-documents/evilhat/fate-condensed_pt-br.md
- data/game-documents/evilhat/fate-core.md
- data/game-documents/evilhat/fate-system-toolkit.md
- data/game-documents/fari-games/charge-rpg.md
- data/game-documents/gameDocuments.ts
- data/game-documents/gamenomicon/second-guess-system.md
- data/game-documents/gilarpgs/lumen.md
- data/game-documents/jasontocci/24xx.md
- data/game-documents/peachgardengames/carta.md
- data/game-documents/peachgardengames/harmony-drive.md
- data/game-documents/rowan-rook-and-decard/resistance-toolbox.md
- data/game-documents/zadmargames/tricube-tales.md
- data/shop/shopProducts.ts
- src/components/Document/Document.tsx
- src/components/MarkdownContent/MarkdownContent.tsx
- src/domains/documents/DocumentParser.tsx
- src/pages/GamePage/GamePage.tsx
- src/pages/PrintGamePage/PrintGamePage.tsx
- src/pages/ShopPage/components/ProductCard.tsx
doc: tricube tales
refac: remove useless doc frontmatter variables
feat: POC with license chips on product cards
> doc: Tricube Tales

- data/game-documents/evilhat/fate-accelerated.md
- data/game-documents/evilhat/fate-adversary-toolkit.md
- data/game-documents/evilhat/fate-condensed.md
- data/game-documents/evilhat/fate-core.md
- data/game-documents/evilhat/fate-system-toolkit.md
- data/shop/shopProducts.ts
- data/shop/types/IShopProduct.ts
- src/components/Document/Document.tsx
- src/pages/GamePage/GamePage.tsx
- src/pages/ShopPage/components/ProductCard.tsx
- src/pages/ShopPage/components/ProductDetails.tsx
- src/pages/ShopPage/components/ProductLicense.tsx
feat: license chips  
feat: document footer
Fixes #7
> feat: license chips and doc footer

- data/game-documents/gameDocuments.ts
- data/game-documents/jesse-ross/trophy-srd.md
- data/shop/shopProducts.ts
- src/pages/SearchPage/SearchPage.tsx
- src/pages/ShopPage/ShopPage.tsx
- src/pages/ShopPage/components/ShopCategory.tsx
> doc: trophy

- data/game-documents/pandion-games/threads-of-lachesis.md
Changes from feedback: Cleaned and simplified verbiage of whole document. Removed duplicate statements. Renamed key words for simplicity, updated images and links to match. Fixed header hierarchy.
Thanks!
-Pandion Games
> Feedback update (Threads of Lachesis)

- data/game-documents/fari-games/charge-rpg.md
Magic cleanup (part 1 of 100, probably)
> doc: charge rpg

- data/game-documents/fari-games/charge-rpg.md
Added examples for magic extra (syntax changes may be required) 
Added assets extra for consistency.
Added Keita's repairs and restoration extra
> doc: charge-rpg.md (magic extra)

- data/game-documents/fari-games/charge-rpg.md
Added Hacks to the Glossary and slightly changed the glossary
> Glossary Update

- data/game-documents/evilhat/fate-accelerated.md
- data/game-documents/evilhat/fate-accelerated_de.md
- data/game-documents/fari-games/charge-rpg.md
- data/game-documents/fari-games/charge-srd.md
- data/game-documents/gameDocuments.ts
- src/components/Document/Document.tsx
- doc: fate turbo
- doc charge
> doc: fate-turbo, charge

- package-lock.json
- package.json
- vite.config.ts
feat: vite reload on markdown change in public folder
feat: vite new react plugin
> feat: vite reload

- public/documents/fari-rpgs/charge-rpg.md
Here's the text of the Party extra converted to Markdown.
> doc: charge-rpg (party-extra)

- public/documents/fari-rpgs/charge-rpg.md
The Threat Level Extra, ready to be review 🎉
> doc: charge-rpg (threat level extra)

- public/documents/fari-rpgs/charge-rpg.md
Text for https://itch.io/t/1882796/money-and-economy-extra
> feat: economy extra

- public/documents/fari-rpgs/charge-rpg.md
Integrates The Resource Pool Extra from itch
https://itch.io/t/1878201/extra-resource-pool-pending
> feat: resource pool extra

- public/documents/fari-rpgs/charge-srd.md
- public/documents/fari-rpgs/charge-srd_fr.md
- src/components/Document/Document.tsx
This PR includes the French version of the Charge SRD translated by the community
> doc: Charge SRD - French Version

- public/documents/fari-rpgs/charge-rpg.md
- public/documents/fari-rpgs/charge-srd.md
- public/documents/fari-rpgs/dash.md
This PR updates the content of Charge, the Charge SRD and Dash to highlight that **Fortune Roll** can be used to make actions as well be won't feature momentum nor consequences.
> doc: Charge v1.1 (fortune roll)

- public/documents/fari-rpgs/charge-rpg.md
- public/documents/fari-rpgs/charge-srd.md
- public/documents/fari-rpgs/dash.md
> Revert "doc: Charge v1.1 (fortune roll)"

- public/documents/fari-rpgs/breathless-srd.md
just a couple formatting things!
> Updates to the Crafting Gasp

- public/documents/fari-rpgs/breathless-srd.md
sorry, spotted another funky spacing issue. should be good now
> medkit spacing update - crafting

- public/documents/fari-rpgs/breathless-srd.md
Introduces the gasp from Task Force JADE
> Investigation checks - Breathless Gasp

- public/documents/fari-rpgs/dash_fr.md
closes #61
For this French translation, I've tried to use as much as possible the current French translation of Charge SRD, which is available in the same repository. Some paragraphs and terms are directly copied from it, and I'd like to thank the translators for their remarkable work.
Although, I've adopted a major change I want to explicit here. The English term _momentum_ was translated as _initiative_ in the Charge translation. Personally, I felt it didn't fit the idea of a pushing-forward force, something that was increasing the pace of the action as the story progresses. "Initiative" felt like something happening at the _beginning_ of the story, and not throughout it.
So I've picked the French word _impulsion_, because I think it reflects the idea I've expressed just above: …
> Added French version of Dash (Fari Games)

- public/documents/fari-rpgs/fari-app-wiki.md
Ran a spellchecker on the wiki. I tried to only suggest uncontroversial changes, clear spelling errors. Should be self-explanatory :o)
> Grammarly spell check
